Caesar_django/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('Caesarcipher.urls', namespace='caesarCipher'))
]

Caesarcipher/urls.py
from django.conf.urls import url
from . import views


urlpatterns = (
    url(r'^decrypt_text/', views.decrypt_text, name='decrypt_text'),
    url(r'^encrypt_text/', views.encrypt_text, name='encrypt_text'),
    url(r'^detect_rot/', views.detect_rot, name='detect'),
    url(r'^bruted/', views.bruted, name='bruted'),
    url(r'^$', views.caesar_cipher_page, name='caesar_cipher_page'),
)

Caesarcipher/models.py
from django.db import models

# Create your models here.

Caesarcipher/views.py
from django.shortcuts import render
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from .cipher import CaesarCipher
import json


def caesar_cipher_page(request):
    data = dict()
    data['rotations'] = range(26)
    return render(request, 'caesar_cipher/index.html', data)


@require_POST
def encrypt_text(request):

    incoming_json = request.body.decode('utf-8')
    json_dict = json.loads(incoming_json)
    text = CaesarCipher(json_dict['text_for_encrypt'])
    data = dict()
    data['ciphered_text'] = text.caesar_main(int(json_dict['rotation']))
    data['count_let'] = [i for i in text.count()]
    data['count_f'] = [text.count()[i] for i in text.count()]
    print(data['count_f'])
    print(data['count_let'])
    return JsonResponse(data)


@require_POST
def decrypt_text(request):
    incoming_json = request.body.decode('utf-8')
    json_dict = json.loads(incoming_json)
    text = CaesarCipher(json_dict['text_for_decrypt'])
    data = dict()
    data['ciphered_text'] = text.caesar_main(int(json_dict['rotation']), False)
    data['count_let'] = [i for i in text.count()]
    data['count_f'] = [text.count()[i] for i in text.count()]
    return JsonResponse(data)


@require_POST
def bruted(request):
    incoming_json = request.body.decode('utf-8')
    json_dict = json.loads(incoming_json)
    text = CaesarCipher(json_dict['brute_text'])
    data = dict()
    data['bruted'] = ['\n'+' Rotation is ' + str(i) + ' : '+text.brute_force()[i] for i in text.brute_force()]
    data['count_let'] = [i for i in text.count()]
    data['count_f'] = [text.count()[i] for i in text.count()]
    print(data['bruted'])
    return JsonResponse(data)


@require_POST
def detect_rot(request):
    incoming_json = request.body.decode('utf-8')
    json_dict = json.loads(incoming_json)
    text = CaesarCipher(json_dict['detected_num'])
    data = dict()
    data['detect_num'] = text.try_detect_rotation()
    return JsonResponse(data)

Caesarcipher/templates/caesar_cipher/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>Caesar cipher</title>
    <link rel="stylesheet" type="text/css" href="{% static 'caesar_cipher/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'caesar_cipher/css/caesar_cipher.css' %}">
    <script type="text/javascript" src="{% static 'caesar_cipher/js/jquery-1.12.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'caesar_cipher/js/jquery.cookie.js' %}"></script>
    <script type="text/javascript" src="{% static 'caesar_cipher/js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'caesar_cipher/js/caesar_cipher.js' %}"></script>
    <script type="text/javascript" src="{% static 'caesar_cipher/chart.js/Chart.js' %}"></script>

</head>
<body>
<div id="caesar">
    <header id="what_is_cipher"><strong>Caesar cipher</strong> -  also known as Caesar's cipher, the shift cipher,
    Caesar's code or Caesar shift, is one of the simplest and most widely known encryption techniques.
    It is a type of substitution cipher in which each letter in the plaintext is replaced by a letter some fixed number of positions down the alphabet.
    For example, with a left shift of 3, D would be replaced by A, E would become B, and so on.
    The method is named after Julius Caesar, who used it in his private correspondence.</header>
    <div id="content" class="container">
        <div class="row">
            <div class="col-sm-5 ">
                <textarea id="cipher_input" class="caesar_text" autocomplete="off"></textarea>
            </div>
            <div class="col-sm-2 elements">
                <p><select id="rotation_fo_action" class="form-control" autocomplete="off">
                        {% for i in rotations %}
                        <option value="{{ i }}">{{ i }}</option>
                        {% endfor %}
                    </select>
                <p><input id="encrypt_text" type="button" class="btn btn-primary" value="Encrypt text"/></p>
                <p> <input id="decrypt_text" type="button" class="btn btn-primary" value="Decrypt text"/></p>
                <p><input id="brute" type="button" class="btn btn-primary" value="Brute force"/></p>
                <p> <input id="detect_rot" type="button" class="btn btn-primary" value="Try detect"/></p>
            </div>
            {%  csrf_token %}
                <input type='hidden' id="encrypt_text_u" type="button"    value="{% url 'caesarCipher:encrypt_text' %}"/>
                <input type='hidden' id="decrypt_text_u" type="button"  value="{% url 'caesarCipher:decrypt_text' %}"/>
                <input type='hidden' id="brute_u" type="button"  value="{% url 'caesarCipher:bruted' %}"/>
                <input type='hidden' id="detect_rot_u" type="button"  value="{% url 'caesarCipher:detect' %}"/>
            <div class="col-sm-5 ">
                <textarea id="cipher_output" class="caesar_text" readonly="readonly"  autocomplete="off"></textarea>
            </div>
        </div>
        <div  class= 'col-sm-6'  id ='rot'>
        </div>
        <div>
            <canvas id="myChart" ></canvas>
        </div>
    </div>
</div>
</body>
</html>